main: me.enne139.PluginMain
name: Save-coordinates-Plugins
version: 0.5
commands:
  addwp:
    description: save location
    usage: /<command> <nome> [publico]
    aliases: [ awp ]
  delwp:
    description: save location
    usage: /<command> <privato> <nome> <confnome>
  listwp:
    description: save location
    usage: /<command>
    aliases: [ lwp ]