main: me.enne139.PluginMain
name: Save-coordinates-Plugins
version: 0.5
commands:
  addwp:
    description: aggiunge un waypoint
    usage: /addwp [nome] <privato/pubblico>
    aliases: [ awp ]
  delwp:
    description: cancella un waypoint
    usage: /delwp [privato/pubblico] [nome] [conferma_nome]
  listwp:
    description: mostra la lista dei waypoint
    usage: /listwp <privato/pubblico> <info>
    aliases: [ lwp ]