main: me.enne139.PluginMain
name: Save-coordinates-Plugins
version: 0.5
commands:
  addwp:
    description: aggiunge un waypoint
    usage: /addwp [nome] <privato/pubblico>
    aliases: [ wpadd, wpa ]
  delwp:
    description: cancella un waypoint
    usage: /delwp [privato/pubblico] [nome] [conferma_nome]
    aliases: [ wpdel ]
  listwp:
    description: mostra la lista dei waypoint
    usage: /listwp <privato/pubblico> <info>
    aliases: [ wplist, wpl ]
  helptwp:
    description: mostra la lista dei waypoint
    usage: /helptwp
    aliases: [ wphelp, wph ]