main: me.enne139.PluginMain
name: Save-coordinates-Plugins
version: 0.5
commands:
  addwp:
    description: aggiunge un waypoint
    usage: /<command>
    aliases: [ wpadd, wpa ]
  delwp:
    description: cancella un waypoint
    usage: /<command>
    aliases: [ wpdel ]
  listwp:
    description: mostra la lista dei waypoint
    usage: /<command>
    aliases: [ wplist, wpl ]
  helpwp:
    description: mostra la lista dei comandi
    usage: /<command>
    aliases: [ wphelp, wph ]
  getwp:
    description: mostra le cordiane di un waypoint
    usage: /<command>
    aliases: [ wpget, wpg ]
  diswp:
    description: mostra la distanza da un waypoint
    usage: /<command>
    aliases: [ wpdis, wpd ]