main: me.enne139.PluginMain
name: Save-coordinates-Plugins
version: 0.5
commands:
  wpadd:
    description: aggiunge un waypoint
    usage: /<command>
  wpdel:
    description: cancella un waypoint
    usage: /<command>
  wplist:
    description: mostra la lista dei waypoint
    usage: /<command>
  wphelp:
    description: mostra la lista dei comandi
    usage: /<command>
    aliases: [ wph ]
  wpget:
    description: mostra le cordiane di un waypoint
    usage: /<command>
  wpdis:
    description: mostra la distanza da un waypoint
    usage: /<command>
  wpgroup:
    description: gestione gruppi
    usage: /<command>
  wpmebers:
    description: gestione mebri gruppi
    usage: /<command>
  wpshow:
    description: mostra le cordiante del waypoint nelle scorboard
    usage: /<command>