main: me.enne139.PluginMain
name: Save-coordinates-Plugins
version: 0.1
commands:
  savewp:
    description: save location
    usage: /<command>
    aliases: [ swp ]
  delwp:
    description: save location
    usage: /<command>
  listwp:
    description: save location
    usage: /<command>
    aliases: [ lwp ]